---
apiVersion: v1                        # apiVersion - Kubernetes default api version.
kind: Secret                          # Kind - Create Secret object.
metadata:                             # metadata - Here we can define object name, labels and annotaions.
  name: secret-04                     # name - Object name.
type: Opaque                          # type - Opaque is the default Secret type.
data:                                 # data - Store key value pairs & files that will insert to pod/container.
  username-01: YWRtaW4tMDE=           # Create key value pair, value have to encode with base64.
  password-01: cGFzc3dvcmQtMDE=

---
apiVersion: v1
kind: Pod                             # Kind - Create Pod object.
metadata:
  name: secret-env-pod
spec:                                 # spec - How to manage the pod.
  containers:                         # containers - Create containers.
  - name: mycontainer                 # name - Container name
    image: k8s.gcr.io/busybox         # image - Container base image.
    command: ["/bin/sh", "-c"]        # command - Run command when the container is up.
    args:                             # args - Run multiple commands when the container is up.
      - env | grep username;
        env | grep password;
    env:                              # env - Create environment variables on the container.
      - name: username                # name - The name of the environment variable.
        valueFrom:                    # valueFrom - From where to take variable value.
          secretKeyRef:               # secretKeyRef - Take variable value from Secret object.
            name: secret-04           # name - The name of the secret that store the variable.
            key: username-01          # key - The key name of the value in the secret.
      - name: password
        valueFrom:
          secretKeyRef:
            name: secret-04 
            key: password-01
  restartPolicy: Never                # restartPolicy - we dont wanna restart the container after its finish to run.
