# Example-02

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: key-value-02
data:
  key_01: "value_01"
  key_02: "value_02"


---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-02
spec:
  containers:
    - name: test-container-02
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: key-value-02
  restartPolicy: Never

