# Example-05

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multiple-data
data:
  key_02: "value_02"
  key_03: "value_03"
  file-02.txt: |
    line-01 on file-02.txt
    line-02 on file-02.txt    
  file-03.txt: |
    line-01 on file-03.txt
    line-02 on file-03.txt
    line-03 on file-03.txt   

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-05
spec:
  containers:
    - name: test-container-05
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo "print env:";
          env | grep var_name_01;
          echo "var_name_02=$(var_name_02)";
          echo "check /etc/config path:";
          ls -la /etc/config;
          echo "cat files in /etc/config/:";
          cat /etc/config/file-02.txt;
          cat /etc/config/file-03.txt;
      env:
        - name: var_name_01
          valueFrom:
            configMapKeyRef:
              name: multiple-data
              key: key_02
        - name: var_name_02
          valueFrom:
            configMapKeyRef:
              name: multiple-data
              key: key_03      
      volumeMounts:
      - name: config-volume-01
        mountPath: /etc/config
  volumes:
    - name: config-volume-01
      configMap:
        name: multiple-data
        items:
        - key: file-02.txt
          path: file-02.txt
        - key: file-03.txt
          path: file-03.txt        
  restartPolicy: Never

