# Example-04

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: file-00
data:   
  file-00.txt: |
    line-01 on file-00.txt
    line-02 on file-00.txt
    line-03 on file-00.txt

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-04
spec:
  containers:
    - name: test-container-04
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "cat /etc/config/file-00.txt" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: file-00
  restartPolicy: Never

