# Example-03

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: key-value-03
data:
  key_03: "value_03"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: key-value-04
data:
  key_04: "value_04"

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-03
spec:
  containers:
    - name: test-container-03
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: var_name_03
          valueFrom:
            configMapKeyRef:
              name: key-value-03
              key: key_03
        - name: var_name_04
          valueFrom:
            configMapKeyRef:
              name: key-value-04
              key: key_04
  restartPolicy: Never


